import { Brand, Vehicle, CustomizationAsset } from './types';

export const mockBrands: Brand[] = [
  {
    id: '1',
    name: 'Apex Motors',
    logo: '🏛️',
    description: 'Premium performance vehicles with cutting-edge technology',
    founded: 2010,
    foundedYear: 2010,
    country: 'USA',
    createdAt: new Date('2024-01-15'),
  },
  {
    id: '2',
    name: 'Velocity Dynamics',
    logo: '⚡',
    description: 'High-speed racing and luxury sports cars',
    founded: 2008,
    foundedYear: 2008,
    country: 'Germany',
    createdAt: new Date('2024-01-10'),
  },
  {
    id: '3',
    name: 'EliteForge',
    logo: '🔧',
    description: 'Handcrafted luxury vehicles for discerning collectors',
    founded: 2012,
    foundedYear: 2012,
    country: 'Italy',
    createdAt: new Date('2024-01-05'),
  },
  {
    id: '4',
    name: 'QuantumDrive',
    logo: '🚀',
    description: 'Next-generation electric vehicles and autonomous technology',
    founded: 2015,
    foundedYear: 2015,
    country: 'Sweden',
    createdAt: new Date('2023-12-20'),
  },
];

export const mockVehicles: Vehicle[] = [
  {
    id: '1',
    name: 'Apex GT-R',
    brandId: '1',
    vehicleModel: 'GT-R Premium',
    year: 2024,
    basePrice: 89000,
    price: 89000,
    modelUrl: '/models/apex-gt-r.glb',
    thumbnail: '🏎️',
    description: 'Ultra-high-performance supercar with 800hp twin-turbocharged engine',
    engine: 'Twin-Turbo V6',
    horsepower: 800,
    torque: 700,
    acceleration: 2.8,
    topSpeed: 205,
    specs: {
      engine: 'Twin-Turbo V6',
      horsepower: 800,
      torque: 700,
      zeroToSixty: 2.8,
    },
    createdAt: new Date('2024-01-20'),
  },
  {
    id: '2',
    name: 'Velocity RS',
    brandId: '2',
    vehicleModel: 'RS Sport',
    year: 2024,
    basePrice: 95000,
    price: 95000,
    modelUrl: '/models/velocity-rs.glb',
    thumbnail: '🏁',
    description: 'Track-focused racing vehicle with aerodynamic design',
    engine: 'Flat-Plane V8',
    horsepower: 850,
    torque: 750,
    acceleration: 2.7,
    topSpeed: 220,
    specs: {
      engine: 'Flat-Plane V8',
      horsepower: 850,
      torque: 750,
      zeroToSixty: 2.7,
    },
    createdAt: new Date('2024-01-18'),
  },
  {
    id: '3',
    name: 'EliteForge Classico',
    brandId: '3',
    vehicleModel: 'Classico Limited',
    year: 2024,
    basePrice: 125000,
    price: 125000,
    modelUrl: '/models/elite-classico.glb',
    thumbnail: '👑',
    description: 'Handcrafted masterpiece combining classic elegance with modern technology',
    engine: 'Naturally Aspirated V12',
    horsepower: 620,
    torque: 580,
    acceleration: 3.5,
    topSpeed: 195,
    specs: {
      engine: 'Naturally Aspirated V12',
      horsepower: 620,
      torque: 580,
      zeroToSixty: 3.5,
    },
    createdAt: new Date('2024-01-12'),
  },
  {
    id: '4',
    name: 'QuantumDrive X1',
    brandId: '4',
    vehicleModel: 'X1 Autonomous',
    year: 2024,
    basePrice: 78000,
    price: 78000,
    modelUrl: '/models/quantum-x1.glb',
    thumbnail: '⚙️',
    description: 'Electric vehicle with Level 3 autonomous capabilities',
    engine: 'Electric Motor Quad-Rotor',
    horsepower: 600,
    torque: 1000,
    acceleration: 3.2,
    topSpeed: 180,
    specs: {
      engine: 'Electric Motor Quad-Rotor',
      horsepower: 600,
      torque: 1000,
      zeroToSixty: 3.2,
    },
    createdAt: new Date('2024-01-08'),
  },
];

export const mockCustomizationAssets: CustomizationAsset[] = [
  {
    id: '1',
    name: 'Metallic Sapphire Blue',
    category: 'paint',
    description: 'Premium metallic paint with depth and luster',
    price: 2500,
    image: '🔵',
    compatibility: ['1', '2', '3', '4'],
    createdAt: new Date('2024-01-15'),
  },
  {
    id: '2',
    name: 'Carbon Black Pearl',
    category: 'paint',
    description: 'Deep black with subtle pearl finish',
    price: 3000,
    image: '⚫',
    compatibility: ['1', '2', '3'],
    createdAt: new Date('2024-01-14'),
  },
  {
    id: '3',
    name: '20-inch Forged Titanium Wheels',
    category: 'wheels',
    description: 'Ultra-lightweight forged wheels with directional design',
    price: 5500,
    image: '🛞',
    compatibility: ['1', '2', '4'],
    createdAt: new Date('2024-01-13'),
  },
  {
    id: '4',
    name: '21-inch Carbon Fiber Wheels',
    category: 'wheels',
    description: 'Premium carbon fiber construction for maximum performance',
    price: 7200,
    image: '⚫',
    compatibility: ['1', '3'],
    createdAt: new Date('2024-01-12'),
  },
  {
    id: '5',
    name: 'Premium Leather Interior',
    category: 'interior',
    description: 'Hand-stitched premium leather with ambient lighting',
    price: 8000,
    image: '🪑',
    compatibility: ['1', '2', '3', '4'],
    createdAt: new Date('2024-01-11'),
  },
  {
    id: '6',
    name: 'Sport Suspension Kit',
    category: 'performance',
    description: 'Adjustable coilovers with motorsport heritage',
    price: 4500,
    image: '🔧',
    compatibility: ['1', '2'],
    createdAt: new Date('2024-01-10'),
  },
  {
    id: '7',
    name: 'Carbon Fiber Body Kit',
    category: 'exterior',
    description: 'Complete aerodynamic enhancement package',
    price: 12000,
    image: '🏗️',
    compatibility: ['1', '2'],
    createdAt: new Date('2024-01-09'),
  },
  {
    id: '8',
    name: 'ECU Tune Performance Package',
    category: 'performance',
    description: '+50hp with custom ECU reprogramming',
    price: 3200,
    image: '💻',
    compatibility: ['1', '2', '4'],
    createdAt: new Date('2024-01-08'),
  },
];

export const mockAssets = mockCustomizationAssets;
